export default [
  {
    title: '校园名称',
    dataIndex: 'schoolId',
    overHidden: true,
    type: 'select',
    editFormOrder: 1,
    needAutoRender: true,
    dicData: [],
    search: true,
    required: true,
    edit: true,
  },
  {
    title: '教师姓名',
    dataIndex: 'teachername',
    width: 100,
    type: 'select',
    dicData: [],
    selfSelectDic: 'teacherIdArray',
    selfSelectDic2: 'teacherIdArray2',
    required: true,
    editFormOrder: 2,
    search: true,
    edit: true,
    selfKey: 'teacherId',
    paramName: 'teacherId',
  },
  {
    title: '上班时间',
    dataIndex: 'workStart',
    type: 'timePicker',
    bindParamOption: { format: 'HH:mm' },
    width: 100,
    editFormOrder: 3,
    required: true,
    search: true,
    edit: true,
  },
  {
    title: '弹性时间',
    dataIndex: 'flexTime',
    type: 'number',
    width: 100,
    edit: true,
  },
  {
    title: '允许未识别次数',
    dataIndex: 'declarationCount',
    type: 'number',
    width: 130,
    search: true,
  },
  {
    title: 'app申报记录',
    dataIndex: 'declareCount',
    type: 'number',
    width: 100,
    search: true,
  },
  {
    title: '下班时间',
    dataIndex: 'workEnd',
    type: 'timePicker',
    editFormOrder: 4,
    required: true,
    bindParamOption: { format: 'HH:mm' },
    width: 100,
    search: true,
    edit: true,
  },
  {
    title: '休息时间',
    dataIndex: 'restDate',
    type: 'select',
    dicData: [
      { label: '双休', value: '1' },
      { label: '六', value: '2' },
      { label: '日', value: '3' },
      { label: '一', value: '4' },
      { label: '二', value: '5' },
      { label: '三', value: '6' },
      { label: '四', value: '7' },
      { label: '五', value: '8' },
    ],
    needAutoRender: true,
    width: 100,
    search: true,
    edit: true,
  },
  {
    title: '寒假',
    dataIndex: 'winter',
    width: 100,
    type: 'dateRange',
    render: (data, rowData) => {
      return rowData['winterStart'] + '至' + rowData['winterEnd'];
    },
    search: true,
    edit: true,
  },
  {
    title: '暑假',
    type: 'dateRange',
    dataIndex: 'summer',
    render: (data, rowData) => {
      return rowData['summerStart'] + '至' + rowData['summerEnd'];
    },
    search: true,
    edit: true,
  },
  {
    title: '执行周期',
    type: 'dateRange',
    dataIndex: 'cycle',
    render: (data, rowData) => {
      return rowData['cycleStart'] + '至' + rowData['cycleEnd'];
    },
    hidden: true,
    edit: true,
  },
];
