import React from 'react';
import { cityList } from '@/constant';
import PowerTree from './PowerTree';
const provinceList = cityList.map(item => item.province);
const renderPowerTree = () => <PowerTree />;
export default [
  {
    title: '校园名称',
    dataIndex: 'schoolId',
    search: true,
    type: 'select',
    width: 200,
    bindParamOption: { allowClear: true },
    needAutoRender: true,
    dicData: [],
    edit: true,
    overHidden: true,
  },
  {
    title: '所属省份',
    dataIndex: 'povice',
    width: 100,
    bindParamOption: { allowClear: true },
    overHidden: true,
    type: 'select',
    edit: true,
    dicData: provinceList,
    search: true,
  },
  {
    title: '用户名',
    dataIndex: 'userName',
    width: 100,
    overHidden: true,
    edit: true,
    required: true,
  },
  {
    title: '校园账号',
    dataIndex: 'account',
    width: 100,
    overHidden: true,
    edit: true,
    required: true,
    search: true,
  },
  {
    title: '校园密码',
    dataIndex: 'password',
    width: 100,
    editInitValue: () => '******',
    overHidden: true,
    edit: true,
    required: true,
  },
  {
    title: '用户角色',
    dataIndex: 'userType',
    width: 100,
    type: 'select',
    dicData: [
      { value: '1', label: '超管' },
      { value: '2', label: '供应商' },
      { value: '3', label: '校方' },
    ],
    needAutoRender: true,
    overHidden: true,
    edit: true,
    required: true,
  },
  {
    title: '添加时间',
    dataIndex: 'createTime',
    type: 'date',
    overHidden: true,
  },
  {
    title: '系统权限',
    dataIndex: 'roleCodes',
    type: 'renderPowerTree',
    editFormSpan: 24,
    format: value => value.join(','),
    edit: true,
    hidden: true,
    createInitValue: [],
    editInitValue: roleCodes => (roleCodes ? roleCodes.split(',') : ''),
    editRender: renderPowerTree,
  },
];
