import { entryName } from '@/config/env';
export const cityList: Array<{
  province: string;
  city: string[];
}> = [
  { province: '北京市', city: ['北京市'] },
  { province: '天津市', city: ['天津市'] },
  {
    province: '河北省',
    city: [
      '石家庄市',
      '唐山市',
      '秦皇岛市',
      '邯郸市',
      '邢台市',
      '保定市',
      '张家口市',
      '承德市',
      '沧州市',
      '廊坊市',
      '衡水市',
    ],
  },
  {
    province: '山西省',
    city: [
      '太原市',
      '大同市',
      '阳泉市',
      '长治市',
      '晋城市',
      '朔州市',
      '晋中市',
      '运城市',
      '忻州市',
      '临汾市',
      '吕梁市',
    ],
  },
  {
    province: '内蒙古自治区',
    city: [
      '呼和浩特市',
      '包头市',
      '乌海市',
      '赤峰市',
      '通辽市',
      '鄂尔多斯市',
      '呼伦贝尔市',
      '巴彦淖尔市',
      '乌兰察布市',
      '兴安盟',
      '锡林郭勒盟',
      '阿拉善盟',
    ],
  },
  {
    province: '辽宁省',
    city: [
      '沈阳市',
      '大连市',
      '鞍山市',
      '抚顺市',
      '本溪市',
      '丹东市',
      '锦州市',
      '营口市',
      '阜新市',
      '辽阳市',
      '盘锦市',
      '盘锦市',
      '朝阳市',
      '葫芦岛市',
    ],
  },
  {
    province: '吉林省',
    city: [
      '长春市',
      '吉林市',
      '四平市',
      '辽源市',
      '通化市',
      '白山市',
      '松原市',
      '白城市',
      '延边',
    ],
  },
  {
    province: '黑龙江省',
    city: [
      '哈尔滨市',
      '齐齐哈尔市',
      '鸡西市',
      '鹤岗市',
      '双鸭山市',
      '大庆市',
      '伊春市',
      '佳木斯市',
      '七台河市',
      '牡丹江市',
      '黑河市',
      '绥化市',
      '大兴安岭地区',
    ],
  },
  { province: '上海市', city: ['上海市'] },
  {
    province: '江苏省',
    city: [
      '南京市',
      '无锡市',
      '徐州市',
      '常州市',
      '苏州市',
      '南通市',
      '连云港市',
      '淮安市',
      '盐城市',
      '扬州市',
      '镇江市',
      '泰州市',
      '宿迁市',
    ],
  },
  {
    province: '浙江省',
    city: [
      '杭州市',
      '宁波市',
      '温州市',
      '嘉兴市',
      '湖州市',
      '绍兴市',
      '金华市',
      '衢州市',
      '舟山市',
      '台州市',
      '丽水市',
    ],
  },
  {
    province: '安徽省',
    city: [
      '合肥市',
      '芜湖市',
      '蚌埠市',
      '淮南市',
      '马鞍山市',
      '淮北市',
      '铜陵市',
      '安庆市',
      '黄山市',
      '滁州市',
      '阜阳市',
      '宿州市',
      '六安市',
      '亳州市',
      '池州市',
      '宣城市',
    ],
  },
  {
    province: '福建省',
    city: [
      '福州市',
      '厦门市',
      '莆田市',
      '三明市',
      '泉州市',
      '漳州市',
      '南平市',
      '龙岩市',
      '宁德市',
    ],
  },
  {
    province: '江西省',
    city: [
      '南昌市',
      '景德镇市',
      '萍乡市',
      '九江市',
      '新余市',
      '鹰潭市',
      '赣州市',
      '吉安市',
      '宜春市',
      '抚州市',
      '上饶市',
    ],
  },
  {
    province: '山东省',
    city: [
      '济南市',
      '青岛市',
      '淄博市',
      '枣庄市',
      '东营市',
      '烟台市',
      '潍坊市',
      '济宁市',
      '泰安市',
      '威海市',
      '日照市',
      '莱芜市',
      '临沂市',
      '德州市',
      '聊城市',
      '滨州市',
      '菏泽市',
    ],
  },
  {
    province: '河南省',
    city: [
      '郑州市',
      '开封市',
      '洛阳市',
      '平顶山市',
      '安阳市',
      '鹤壁市',
      '新乡市',
      '焦作市',
      '济源市',
      '濮阳市',
      '许昌市',
      '漯河市',
      '三门峡市',
      '南阳市',
      '商丘市',
      '信阳市',
      '周口市',
      '驻马店市',
    ],
  },
  {
    province: '湖北省',
    city: [
      '武汉市',
      '黄石市',
      '十堰市',
      '宜昌市',
      '襄阳市',
      '鄂州市',
      '荆门市',
      '孝感市',
      '荆州市',
      '黄冈市',
      '咸宁市',
      '随州市',
      '恩施',
      '仙桃市',
      '潜江市',
      '天门市',
      '神农架林区',
    ],
  },
  {
    province: '湖南省',
    city: [
      '长沙市',
      '株洲市',
      '湘潭市',
      '衡阳市',
      '邵阳市',
      '岳阳市',
      '常德市',
      '张家界市',
      '益阳市',
      '郴州市',
      '永州市',
      '怀化市',
      '娄底市',
      '湘西',
    ],
  },
  {
    province: '广东省',
    city: [
      '广州市',
      '韶关市',
      '深圳市',
      '珠海市',
      '汕头市',
      '佛山市',
      '江门市',
      '湛江市',
      '茂名市',
      '肇庆市',
      '惠州市',
      '梅州市',
      '汕尾市',
      '河源市',
      '阳江市',
      '清远市',
      '东莞市',
      '中山市',
      '东沙群岛',
      '潮州市',
      '揭阳市',
      '云浮市',
    ],
  },
  {
    province: '广西壮族自治区',
    city: [
      '南宁市',
      '柳州市',
      '桂林市',
      '梧州市',
      '北海市',
      '防城港市',
      '钦州市',
      '贵港市',
      '玉林市',
      '百色市',
      '贺州市',
      '河池市',
      '来宾市',
      '崇左市',
    ],
  },
  {
    province: '海南省',
    city: [
      '海口市',
      '三亚市',
      '三沙市',
      '五指山市',
      '琼海市',
      '儋州市',
      '文昌市',
      '万宁市',
      '东方市',
      '定安县',
      '屯昌县',
      '澄迈县',
      '临高县',
      '白沙',
      '昌江',
      '乐东',
      '陵水',
      '保亭',
      '琼中',
    ],
  },
  { province: '重庆市', city: ['重庆市'] },
  {
    province: '四川省',
    city: [
      '成都市',
      '自贡市',
      '攀枝花市',
      '泸州市',
      '德阳市',
      '绵阳市',
      '广元市',
      '遂宁市',
      '内江市',
      '乐山市',
      '南充市',
      '眉山市',
      '宜宾市',
      '广安市',
      '达州市',
      '雅安市',
      '巴中市',
      '资阳市',
      '阿坝',
      '甘孜',
      '凉山',
    ],
  },
  {
    province: '贵州省',
    city: [
      '贵阳市',
      '六盘水市',
      '遵义市',
      '安顺市',
      '铜仁市',
      '黔西南',
      '毕节市',
      '黔东南',
      '黔南',
    ],
  },
  {
    province: '云南省',
    city: [
      '昆明市',
      '曲靖市',
      '玉溪市',
      '保山市',
      '昭通市',
      '丽江市',
      '普洱市',
      '临沧市',
      '楚雄',
      '红河',
      '文山',
      '西双版纳',
      '大理',
      '德宏',
      '怒江',
      '迪庆',
    ],
  },
  {
    province: '西藏自治区',
    city: [
      '拉萨市',
      '昌都地区',
      '山南地区',
      '日喀则地区',
      '那曲地区',
      '阿里地区',
      '林芝地区',
    ],
  },
  {
    province: '陕西省',
    city: [
      '西安市',
      '铜川市',
      '宝鸡市',
      '咸阳市',
      '渭南市',
      '延安市',
      '汉中市',
      '榆林市',
      '安康市',
      '商洛市',
    ],
  },
  {
    province: '甘肃省',
    city: [
      '兰州市',
      '嘉峪关市',
      '金昌市',
      '白银市',
      '天水市',
      '武威市',
      '张掖市',
      '平凉市',
      '酒泉市',
      '庆阳市',
      '定西市',
      '陇南市',
      '临夏',
      '甘南',
    ],
  },
  {
    province: '青海省',
    city: ['西宁市', '海东市', '海北', '黄南', '海南', '果洛', '玉树', '海西'],
  },
  {
    province: '宁夏回族自治区',
    city: ['银川市', '石嘴山市', '吴忠市', '固原市', '中卫市'],
  },
  {
    province: '新疆维吾尔自治区',
    city: [
      '乌鲁木齐市',
      '克拉玛依市',
      '吐鲁番地区',
      '哈密地区',
      '昌吉',
      '博尔塔拉',
      '巴音郭楞',
      '阿克苏地区',
      '克孜勒苏柯尔克孜自治州',
      '喀什地区',
      '和田地区',
      '伊犁',
      '塔城地区',
      '阿勒泰地区',
      '石河子市',
      '阿拉尔市',
      '图木舒克市',
      '五家渠市',
    ],
  },
];
export const gradeList: Array<{
  value: string;
  label: string;
  children: Array<{
    value: string;
    label: string;
  }>;
}> = [
  {
    value: '小',
    label: '小学',
    children: [
      {
        value: '小一',
        label: '小一',
      },
      {
        value: '小二',
        label: '小二',
      },
      {
        value: '小三',
        label: '小三',
      },
      {
        value: '小四',
        label: '小四',
      },
      {
        value: '小五',
        label: '小五',
      },
      {
        value: '小六',
        label: '小六',
      },
    ],
  },
  {
    value: '初',
    label: '初中',
    children: [
      {
        value: '初一',
        label: '初一',
      },
      {
        value: '初二',
        label: '初二',
      },
      {
        value: '初三',
        label: '初三',
      },
    ],
  },
  {
    value: '高',
    label: '高中',
    children: [
      {
        value: '高一',
        label: '高一',
      },
      {
        value: '高二',
        label: '高二',
      },
      {
        value: '高三',
        label: '高三',
      },
    ],
  },
];

export const classNameList: Array<dicDataObj> = [
  {
    value: '1',
    label: '一班',
  },
  {
    value: '2',
    label: '二班',
  },
  {
    value: '3',
    label: '三班',
  },
  {
    value: '4',
    label: '四班',
  },
  {
    value: '5',
    label: '五班',
  },
  {
    value: '6',
    label: '六班',
  },
  {
    value: '7',
    label: '七班',
  },
  {
    value: '8',
    label: '八班',
  },
  {
    value: '9',
    label: '九班',
  },
  {
    value: '10',
    label: '十班',
  },
  {
    value: '11',
    label: '十一班',
  },
  {
    value: '12',
    label: '十二班',
  },
  {
    value: '13',
    label: '十三班',
  },
  {
    value: '14',
    label: '十四班',
  },
  {
    value: '15',
    label: '十五班',
  },
  {
    value: '16',
    label: '十六班',
  },
  {
    value: '17',
    label: '十七班',
  },
  {
    value: '18',
    label: '十八班',
  },
  {
    value: '19',
    label: '十九班',
  },
  {
    value: '20',
    label: '二十班',
  },
];

export const ascAndDesc: stringObj = {
  ascend: '1',
  descend: '2',
};

export const levelTypes: stringObj = {
  小: '小学',
  初: '初中',
  高: '高中',
};
/**
 * string: Must be of type string. This is the default type.
 * number: Must be of type number.
 * boolean: Must be of type boolean.
 * method: Must be of type function.
 * regexp: Must be an instance of RegExp or a string that does not generate an exception when creating a new RegExp.
 * integer: Must be of type number and an integer.
 * float: Must be of type number and a floating point number.
 * array: Must be an array as determined by Array.isArray.
 * object: Must be of type object and not Array.isArray.
 * enum: Value must exist in the enum.
 * date: Value must be valid as determined by Date
 * url: Must be of type url.
 * hex: Must be of type hex.
 * email: Must be of type email.
 * any: Can be any type.
 * */
export const defaultValidType: stringObj = {
  date: 'date',
  dateRange: 'array',
  multipleSelect: 'array',
  number: 'number',
  numberRange: 'number',
  timePicker: 'object',
  renderPowerTree: 'array',
};
export const courseType1: stringObj = {
  '1': '早自习',
  '2': '上午',
  '3': '下午',
  '4': '晚自习',
};
export const staticWeek: Array<string> = [
  'week1',
  'week2',
  'week3',
  'week4',
  'week5',
  'week6',
  'week7',
];
// 静态路由
export const staticRouter: Array<selfRoute> = [
  {
    path: '/dataManager',
    component: '',
    children: [
      {
        path: entryName + '/sys/dataManager/schoolManage',
        component: 'views/dataManager/schoolManage',
        children: [],
        icon: '',
        id: '2-1',
        parentId: '2',
        label: '学校管理',
        Abbreviation: '学校',
        describe:
          '把您已合作的学校通过该模块管理。通过记录学校的区域、校园名称，logo等数据形成校园表单，当您有新的合作学校时也通过该模块进行添加。',
      },
      {
        path: entryName + '/sys/dataManager/classManage',
        component: 'views/dataManager/classManage',
        children: [],
        icon: '',
        id: '2-2',
        parentId: '2',
        label: '班级管理',
        Abbreviation: '班级',
        describe:
          '通过之前的校园管理，平台已经帮您把大类别学校进行管理，班级管理是针对每所不同学校，进行年级和班级的有效管理。',
      },
      {
        path: entryName + '/sys/dataManager/studentManage',
        component: 'views/dataManager/studentManage',
        children: [],
        icon: '',
        id: '2-3',
        parentId: '2',
        label: '学生管理',
        Abbreviation: '学生',
        describe:
          '通过之前的班级管理，平台已经帮您把大类别班级进行管理，学生管理是针对每个不同班级，进行学生的有效管理。',
      },
      {
        path: entryName + '/sys/dataManager/teacherManage',
        component: 'views/dataManager/teacherManage',
        children: [],
        icon: '',
        id: '2-4',
        parentId: '2',
        label: '教师管理',
        Abbreviation: '教师',
        describe:
          '通过之前的班级与学校管理，平台已经帮您把大类别班级与学校进行管理，教师管理是针对每个不同学校，进行教师的有效管理。',
      },
    ],
    icon: 'database',
    id: '2',
    label: '数据管理',
  },
  {
    path: '/attendanceMag',
    component: '',
    children: [
      {
        path: entryName + '/sys/attendanceMag/stuAttendance',
        component: 'views/attendanceMag/stuAttendance',
        children: [],
        icon: '',
        id: '3-1',
        parentId: '3',
        label: '学生考勤设置',
        Abbreviation: '学生考勤',
        describe: '通过摄像头与AI技术对学生的考勤进行有效管理。',
      },
      {
        path: entryName + '/sys/attendanceMag/thrAttendance',
        component: 'views/attendanceMag/thrAttendance',
        children: [],
        icon: '',
        id: '3-2',
        parentId: '3',
        label: '教师考勤设置',
        Abbreviation: '教师考勤',
        describe: '通过摄像头与AI技术对教师的考勤进行有效管理。',
      },
      {
        path: entryName + '/sys/attendanceMag/thrExDeclaration',
        component: 'views/attendanceMag/thrExDeclaration',
        children: [],
        icon: '',
        id: '3-3',
        parentId: '3',
        label: '教师异常申报',
        Abbreviation: '教师异常',
        describe: '对教师的考勤异常申报进行有效管理。',
      },
    ],
    icon: 'calendar',
    id: '3',
    label: '考勤管理',
  },
  {
    path: '/informationManager',
    component: '',
    children: [
      {
        path: entryName + '/sys/informationManager/bannerManage',
        component: 'views/informationManager/bannerManage',
        children: [],
        icon: '',
        id: '4-1',
        parentId: '4',
        label: 'banner管理',
        Abbreviation: 'banner',
        describe: '对校园的banner进行有效管理。',
      },
      {
        path: entryName + '/sys/informationManager/schoolNews',
        component: 'views/informationManager/schoolNews',
        children: [],
        icon: '',
        id: '4-2',
        parentId: '4',
        label: '校内新闻',
        Abbreviation: '校内新闻',
        describe: '对校内新闻进行有效管理。',
      },
      {
        path: entryName + '/sys/informationManager/curriculumManage',
        component: 'views/informationManager/curriculumManage',
        children: [],
        icon: '',
        id: '4-3',
        parentId: '4',
        label: '课程表管理',
        Abbreviation: '课程表',
        describe: '对各个班级的课程表进行有效管理。',
      },
      /*{
        'path': entryName + '/sys/informationManager/resultsManage',
        'component': 'views/informationManager/resultsManage',
        'children': [],
        'icon': '',
        'id': '4-5',
        'parentId': '4',
        'label': '学生成绩管理',
        'Abbreviation': '学生成绩',
        'describe': '对各个学生的成绩进行有效管理。'
      },*/
    ],
    icon: 'alert',
    id: '4',
    label: '信息管理',
  },
  {
    path: '/leaveManage',
    component: '',
    children: [
      {
        path: entryName + '/sys/leaveManage/stuLeaveRecord',
        component: 'views/leaveManage/stuLeaveRecord',
        children: [],
        icon: '',
        id: '5-1',
        parentId: '5',
        label: '学生请假记录',
        Abbreviation: '学生请假',
        describe: '对各个学生的请假记录进行有效管理。',
      },
      {
        path: entryName + '/sys/leaveManage/teacherLeaveReview',
        component: 'views/leaveManage/teacherLeaveReview',
        children: [],
        icon: '',
        id: '5-2',
        parentId: '5',
        label: '教师请假审核',
        Abbreviation: '教师请假',
        describe: '对各个教师的请假记录进行有效管理。',
      },
    ],
    icon: 'thunderbolt',
    id: '5',
    label: '请假管理',
  },
  {
    path: '/faceRecognition',
    component: '',
    children: [
      {
        path: entryName + '/sys/faceRecognition/studentFaceRecord',
        component: 'views/faceRecognition/studentFaceRecord',
        children: [],
        icon: '',
        id: '6-1',
        parentId: '6',
        label: '学生人脸记录',
        Abbreviation: '学生人脸',
        describe: '对各个学生的人脸记录进行有效管理。',
      },
      {
        path: entryName + '/sys/faceRecognition/teacherFaceRecord',
        component: 'views/faceRecognition/teacherFaceRecord',
        children: [],
        icon: '',
        id: '6-2',
        parentId: '6',
        label: '教师人脸记录',
        Abbreviation: '教师人脸',
        describe: '对各个教师的人脸记录进行有效管理。',
      },
      {
        path: entryName + '/sys/faceRecognition/strangerFaceRecord',
        component: 'views/faceRecognition/strangerFaceRecord',
        children: [],
        icon: '',
        id: '6-3',
        parentId: '6',
        label: '陌生人人脸记录',
        Abbreviation: '陌生人人脸',
        describe: '对各个陌生人的人脸记录进行有效管理。',
      },
    ],
    icon: 'contacts',
    id: '6',
    label: '人脸管理',
  },
  {
    path: entryName + '/sys/paymentRecord',
    component: 'views/paymentRecord/index',
    children: [],
    icon: 'account-book',
    id: '7-1',
    label: '支付记录查询',
    Abbreviation: '支付记录',
    describe: '对各个用户的支付记录进行有效管理。',
  },
  {
    path: entryName + '/sys/powerManage',
    component: 'views/powerManage/index',
    children: [],
    icon: 'apartment',
    id: '8-1',
    label: '权限管理',
    Abbreviation: '权限',
    describe: '对系统各个账号的进行有效的权限管理。',
  },
  {
    path: entryName + '/sys/equipmentManage',
    component: 'views/equipmentManage/index',
    children: [],
    icon: 'tool',
    id: '9-1',
    label: '硬件管理',
    Abbreviation: '硬件',
    describe: '对各个学校的硬件设备进行有效管理。',
  },
];
export const qjlx: Array<dicDataObj> = [
  { value: '1', label: '病假' },
  { value: '2', label: '事假' },
];
export const allDateData: string[] = [
  'timePicker',
  'dateRange',
  'date',
  'dateTimePicker',
  'monthPicker',
  'timeRange',
];
export const defaultFormat: stringObj = {
  timePicker: 'HH:mm',
  dateRange: 'YYYY-MM-DD',
  date: 'YYYY-MM-DD',
  dateTimePicker: 'YYYY-MM-DD HH:mm',
  monthPicker: 'YYYY-MM',
  timeRange: 'YYYY-MM-DD HH:mm',
};

export const classTypes: Array<dicDataObj> = [
  { label: '小学', value: '小' },
  { label: '初中', value: '初' },
  { label: '高中', value: '高' },
];
